apiVersion: apps/v1
kind: Deployment
metadata:
    name: flan-scan-deployment
    namespace: flan
    labels:
        app: flan-scan
spec:
   replicas: 1
   selector:
       matchLabels:
           app: flan-scan
   template:
       metadata:
           labels:
               app: flan-scan
       spec:
           volumes:
           # - emptyDir:
           #   name: shared
           - name: shared-files
             configMap:
                name: shared-files
                items:
                - key: ips.txt
                  path: ips.txt
           # securityContext:
           #   privileged: true
           containers:
           - name: flan-scan-svc
             image: berndonline/flan:latest
             imagePullPolicy: Always
             volumeMounts:
             # - name: shared
             #   mountPath: /shared
             - name: shared-files
               mountPath: /shared/ips.txt
               subPath: ips.txt
             env:
             - name: format
               value: html
             - name: clustername
               value: <-cluster-name->
             - name: upload
               value: aws
             - name: bucket
               value: <-name->
             envFrom:
             - secretRef:
                 name: cloud-creds
