name: ci
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: build and tag container image
      run: |
        make build
        docker tag flan_scan:latest berndonline/flan:latest

    - name: push container image
      run: |
        docker login -u "${REGISTRY_USER}" -p "${REGISTRY_TOKEN}"
        docker push berndonline/flan:latest
      env:
        REGISTRY_TOKEN: ${{ secrets.docker_token }}
        REGISTRY_USER: ${{ secrets.docker_username }}  
